### PR TITLE
add check when table 'counters' is absent

### PR DESCRIPTION
**Pull request by rda1902**
I try fix error when project doesn't have 'counters' table, but have two different migration to create counter_cache fields in two tables, and code for counter_cache  was added to model in before wrote migration. In processing first migration work (create counter_cache fields for first table) raise error that counter_cache fields absent in second table, because second migration doesn't worked yet.

### CODE REVIEW

**Comment by cedric** [comment]
@rda1902 I'm not sure I follow the problem. The code should not work if there is neither a counter cache field or a counters table. Migrations should be run to add a field before any code that uses it is introduced. Rather than stub the cache column with an accessor, we could raise an actual error -- but I don't think that is what you're after.

**Comment by rda1902** [comment]
Ok, i see you point, but for example i work on two computers, on work i installed this gem, created migrations and added code to models. Work fine! When i came to home and tried apply new migration, on home computer, i received error that counter cache field was absent and migration did not work. Without my additions i could not apply migration and continue work.

**Comment by cedric** [comment]
I hear you, but it seems like a workflow problem more than anything. If you have a migration to add a column and have code that uses it, you need to first deploy and run the migration, then deploy the code that uses it (which also restarts the app post-migration). If you use two computers, then you need to first merge the branch with the migration, then merge the code that uses it. This gem is no different. You shouldn't merge code that uses a column or table that doesn't exist yet. I'm open to raising an explicit error, but it seems odd to add an unused attribute accessor. Otherwise, I could disable the functionality entirely, perhaps even log it to the console. I'm just not sure this is worth it.

**Comment by cedric** [comment]
We could certainly look into either disabling the mixin entirely if the field or table is missing or we could raise an explicit error. I don't plan on working on this right now, so unless you want to I'm going to go ahead and close this PR. Regardless, thank you for your contribution.

**Pull request closed without merging**
